---
title: "aim1_outcome_exp"
author: "Wanjing Chen"
date: "2024-04-08"
output:
  word_document: default
  html_document: default
  pdf_document: default
header-includes: "\\usepackage{booktabs} - \\usepackage{longtable}"
---


```{r}
var_full <- readRDS("processed_meta.rds")
scd_data_yr3_label <- readRDS("cleaned_scd_data.rds")
naming_vec <- readRDS("var_labels.RDS")
df_lst <- readRDS("cleaned_categorized_dfsubset.RDS")
source("R/var_cat_test.R")
source("R/var_cat_plot.R")
```

```{r}
outcome_df <- df_lst$Outcomes |>
  select_at(vars(-starts_with("INT")))

pred_disease_df <- df_lst$`Disease-related`
pred_patient_df <- df_lst$`Patient-related`
pred_transp_df <- df_lst$`Tranplant-related`
```


```{r}
cat_disease_df <- pred_disease_df %>%
  select(where(~ !is.numeric(.)))
  
cat_patient_df <- pred_patient_df %>%
  select(where(~ !is.numeric(.)), 
         -DUMMYID)

cat_transp_df <- pred_transp_df %>%
  select(where(~ !is.numeric(.)),
         YEARTX)

```



```{r}
dat1 <- cat_test(outcome_df, cat_disease_df)
dat2 <- cat_test(outcome_df, cat_patient_df)
dat3 <- cat_test(outcome_df, cat_transp_df)



dat1[[2]]$Outcome <- naming_vec[tolower(dat1[[2]]$Outcome)]
dat1[[2]]$Explanatory <- naming_vec[tolower(dat1[[2]]$Explanatory)]




dat2[[2]]$Outcome <- naming_vec[tolower(dat2[[2]]$Outcome)]
dat2[[2]]$Explanatory <- naming_vec[tolower(dat2[[2]]$Explanatory)]

dat2[[2]] |> filter(Pvalue <= 0.05) |>
  filter(!str_detect(Explanatory, "Cases from"))





dat3[[2]]$Outcome <- naming_vec[tolower(dat3[[2]]$Outcome)]
dat3[[2]]$Explanatory <- naming_vec[tolower(dat3[[2]]$Explanatory)]

dat3[[2]] |> filter(Pvalue <= 0.05) |>
  filter(!str_detect(Explanatory, "Cases from"))
```


```{r}
cat_plot(outcome_df, cat_disease_df, naming_vec)
cat_plot(outcome_df, cat_patient_df, naming_vec)
cat_plot(outcome_df, cat_transp_df, naming_vec)

```




```{r}
num_disease_df <- pred_disease_df %>%
  select(where(~ is.numeric(.)))
  
num_patient_df <- pred_patient_df %>%
  select(where(~ is.numeric(.)), 
         -DUMMYID)

num_transp_df <- pred_transp_df %>%
  select(where(~ is.numeric(.)), 
         -YEARTX) #YEARTX should be seen as categorical


num_df <- cbind(outcome_df, 
                num_patient_df)


lapply(colnames(outcome_df), function(out_i){
  dt <- num_df[ , c(out_i, "AGE")]

  ret1 <- dt |>
    group_by(!!sym(out_i))|>
    summarize(Total_num = n(),
              Avg_age = mean(AGE), 
              Med_age = median(AGE))

  
  ret2 <- ggplot(dt) + 
    geom_density(aes(x = AGE, fill = !!sym(out_i)), 
                 alpha = 0.3) 
  
  list(ret1, ret2)
})

```