---
title: "aim1_tables"
author: "Wanjing Chen"
date: "2024-04-07"
output:
  word_document: default
  html_document: default
  pdf_document: default
header-includes: "\\usepackage{booktabs} - \\usepackage{longtable}"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
```


```{r}
source("R/summarize_data.R")
var_full <- readRDS("processed_meta.rds")
scd_data_yr3_label <- readRDS("processed_scd_data.rds")
```



```{r}
naming_vec <- setNames(var_full$Description, 
                       var_full$Variable.name)


naming_vec["age"] <- "Age (Years)"
naming_vec["agegpff"] <- "Age Categories (Years)"
naming_vec["yeargpf"] <- "Year of Transplant Categories (Year)"
naming_vec["yeartx"] <- "Year of Translplant (Year)"


var_Cats <- var_full |> 
  group_by(Category) |>
  mutate(all_vars = paste0(Variable.name, collapse = ","))|>
  select(Category, all_vars)|>
  ungroup()|>
  distinct()

df_lst <- setNames(lapply(var_Cats$Category, function(cat_i){
  cols <- var_Cats[var_Cats$Category == cat_i, ]$all_vars %>%
    strsplit(., ",") %>%
    unlist()
  ret <- scd_data_yr3_label[, toupper(cols), drop = F]
  return(ret)
}), var_Cats$Category)




data_summary <- lapply(seq_len(length(df_lst)), function(i){
  df_i <- df_lst[[i]]
  
  exclude = NULL
  id = NULL
  if("RACEGP" %in% colnames(df_i)){
    exclude  = c(exclude, "RACEGP")
  }
  if("YEARTX" %in% colnames(df_i)){
    exclude = c(exclude, "YEARTX")
  }
  if("DUMMYID" %in% colnames(df_i)){
    id = c(id, "DUMMYID")
  }
  ret <- summarize_data(df_i, id, 
                 exclude, naming_vec, 
                 names(df_lst)[i])
  
})


```